#!/usr/bin/env sh
PROJECT_ROOT=$HOME;
PROJECT_NAME="MyProject";
PROJECT_URL="myproject.local";

GIT_REPOSITORY="git@github.com:laravel/laravel.git";
GIT_FOLDER_NAME="my-laravel-project";
GIT_NAME="John Doe";
GIT_EMAIL="john.doe@email.com";

HOMESTEAD_IP_ADDRESS="192.168.100.10";
REPOSITORY_FOLDER="repositories";
HOMESTEAD_NAME="myproject";
HOMESTEAD_HOSTNAME="myproject";

DB_DATABASE="myproject";
